### ISSUE TITLE
(Question) Lines on map

### ISSUE THREAD

**Issue by alphafox02** [kdudkov/goatak#13]
Is it possible goatak client could display lines on the map if sent CoT message in such a way that would generate a line originating from gps location of the client?

**Comment by alphafox02** [comment]
I’ve updated the title and have a better example now. The following repository allows for the ability to send KrakenSDR information in CoT format to a Tak server where lines are draw according to what they should be as generated by the KrakenSDR.

https://github.com/canaryradio/Kraken-to-TAK-Python

While goatak will display the location point of the KrakenSDR itself when connect to the TakServer, it does not display the generated lines of bearing. I’m assuming that maybe goatak does not understand the format?

**Comment by kdudkov** [comment]
Public goatac version doesn't support drawing on map`u-` messages, like lines and polygons.

**Comment by alphafox02** [comment]
I can create a separate suggest/request ticket if needed but I wanted to share this thought with you. If you get it to where the lines and shapes can be drawn/accounted for, perhaps have a look at this project and the algorithm behind it. 

If it could be pulled into your project as a “plugin” for the client it could perhaps allow the lines that are pulled into the goatak client from server or even locally to be calculated in such a way the signal source could be located when one (mobile) or more KrakenSDRs are used. They could even be stationary. 

https://github.com/ckoval7/df-aggregator/blob/master/df-aggregator.py

**Comment by alphafox02** [comment]
I didn’t mean to close the ticket.
