### ISSUE TITLE
Broadcasting COTs are seen from all Scopes

### ISSUE THREAD

**Issue by kavinsky** [kdudkov/goatak#17]
Steps to reproduce:

1. Login using WinTAK using an account with scope: scopeA
2. Login with other device using an account with scope: scopeB
3. Create a COT with Account A and press Broadcast.
4. Scope B can see the broadcasted COT

**Comment by kdudkov** [comment]
When two clients are in the same network, they broadcast all cots via TCP broadcast if this function is not disabled. And this way they could see all messages regardless of scope.

**Comment by kavinsky** [comment]
As we talked, i think having the option to restrict visibility of messages by scope is a nice have. Ill close this issue and make a PR for that. Thank you.
