### ISSUE TITLE
a unexpected http respone from server 

### ISSUE THREAD

**Issue by 8423ffsf** [kdudkov/goatak#22]
I use openssl for a self-signed ca, and set the server.yml. I tried the client this program with ssl ,but the error came.Here is the log from the client:
C:\Users\Administrator\Desktop\client_0.19.1_windows_amd64>goatak_client.exe
[37m[23:05:28.779][0m [92mINFO[0m [97mcallsign: yuki-web[0m
[37m[23:05:28.800][0m [92mINFO[0m [97muid: ANDROID-79756b692d776562[0m
[37m[23:05:28.801][0m [92mINFO[0m [97mteam: Orange[0m
[37m[23:05:28.801][0m [92mINFO[0m [97mrole: Forward Observer[0m
[37m[23:05:28.801][0m [92mINFO[0m [97mserver: 192.168.1.99:8089:ssl[0m
[37m[23:05:28.801][0m [92mINFO[0m [97mgetting tls config[0m [90m{"logger":"enroller"}[0m
[37m[23:05:28.803][0m [92mINFO[0m [97mGET https://192.168.1.99:8446/Marti/api/tls/config - error Get "https://192.168.1.99:8446/Marti/api/tls/config": http: server gave HTTP response to HTTPS client[0m [90m{"logger":"enroller"}[0m
[37m[23:05:28.803][0m [91mERROR[0m [97merror while enroll cert: Get "https://192.168.1.99:8446/Marti/api/tls/config": http: server gave HTTP response to HTTPS client[0m]

and here is the server.yml
---
 admin api listener
admin_addr: ":8088"
  Marti api listener. Port should be 8080 for no ssl and 8443 for ssl. If ssl is configured (ssl.use_ssl=true)
  cerver certificate is used
api_addr: ":8443"
  Certificate enrollment listener. You must provide external certificate validation, not server cert!
cert_addr: ":8446"
  TCP stream listener
tcp_addr: ":8999"
  UDP stream listener
udp_addr: ":8999"
  TCP TLS listener for ATAK clients. Port should be 8089
ssl_addr: ":8089"
  if true server will save all messages to files in data/log folder
log: true
  directory for all server data (default is "data")
data_dir: data
  file with user creds and settings (default is "users.yml")
users_file: users.yml
  Webtak files root folder
webtak_root: ""
  enable Datasync/missions api
datasync: true

me:
  lat: 35.462939
  lon: -97.537283
  zoom: 5

ssl:
  use_ssl: true
  ca: cert/cacert.pem
  cert: cert/cert.pem
  key: cert/cert.key
     enrolled cert ttl in days (default is 365)
  cert_ttl_days: 365

server ver:0.19.1(runnig on windows)
(all "#" in config has been removed in this issue text)

**Comment by kdudkov** [comment]
> login for cert enrollment. If not empty, client does cert enrollment

In your configuration, client tries to do certificate enrollment. 

On server side you must provide external ssl termination, usually nginx server. Goatak server itself handles http on this port.

**Comment by 8423ffsf** [comment]
after proxy,it works.
