### ISSUE TITLE
A quick question...

### ISSUE THREAD

**Issue by 5tubb0rn** [kdudkov/goatak#6]
Im attempting to install this on a raspberry pi. The docker command gives me this:

"WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec ./goatak_server: exec format error"

Is there no docker for Arm64?

**Comment by kdudkov** [comment]
just pushed `linux/arm/v7`, `linux/arm64/v8` with `latest` tag

**Comment by kdudkov** [comment]
new release with linux/arm6 & linux/arm7 archives: https://github.com/kdudkov/goatak/releases/tag/v0.14.5
