### ISSUE TITLE
Duplicated message to Freetakserver 

### ISSUE THREAD

**Issue by alphafox02** [kdudkov/goatak#9]
22.04 with GoAtak client connected to the free Freetakserver online.

When sending a message it appears duplicated  in list of messages. For example, when connecting to the Freetakserver you get the first intro message. Sending a message such as “test” and going to view messages shows it twice and message found goes from one (initial welcome message) to account of three. In the console where goatak client is running it also appears there’s an issue getting a list of clients, but I will double check again. 

Is this a known incompatibility with Freetakserver?

**Comment by alphafox02** [comment]
As a follow up, testing the goatak client against the official TAK server has good results. I do not currently see the duplicated message like I did when testing against the public FreeTakServer.

**Comment by kdudkov** [comment]
> As a follow up, testing the goatak client against the official TAK server has good results. I do not currently see the duplicated message like I did when testing against the public FreeTakServer.

I didn't find any duplicate messages either. I'm guessing this might be an FTS issue.

**Comment by alphafox02** [comment]
Likely a FTS issue, closing.
